---
abstract: 'Wrapper around the Jena rule engine command line interface'
author:
  - 'konstantin baierer <kba@cpan.org>'
build_requires:
  Archive::Extract: 0.48
  LWP::UserAgent: 6.03
  Module::Build: 0.38
  MooseX::NonMoose: 0.16
  POSIX: 1.24
  Pod::Readme: 0.11
  Pod::Select: 1.36
configure_requires:
  Archive::Extract: 0.48
  LWP::UserAgent: 6.03
  Module::Build: 0.38
  MooseX::NonMoose: 0.16
  POSIX: 1.24
  Pod::Readme: 0.11
  Pod::Select: 1.36
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RDF-TrineX-RuleEngine-Jena
provides:
  RDF::TrineX::RuleEngine::Jena:
    file: lib/RDF/TrineX/RuleEngine/Jena.pm
    version: 0.001
requires:
  Archive::Zip: 1.30
  Carp: 1.20
  Data::Dumper: 2.130_02
  English: 1.04
  File::Copy: 2.21
  File::Find: 1.19
  File::Share: 0.02
  File::Slurp: 9999.19
  File::Temp: 0.22
  IO::CaptureOutput: 1.1102
  Moose: 2.0205
  Path::Class: 0.18
  RDF::Trine: 0.136
  Try::Tiny: 0.09
resources:
  license: http://dev.perl.org/licenses/
version: 0.001
